[project]
name = "rescreener"
version = "0.1.0"
keywords = [ "AI", "ML", "NLP", "LLM" ]
description = "AI-Powered Resume Screener (Classification + NLP + LLM)"
authors = [
    {name = "Rubens Gomes", email = "rubens.s.gomes@gmail.com"}
]
license = "Apache License Version 2.0"
readme = "README.md"
documentation = "https://github.com/rubensgomes/rescreener/README.md"
repository = "https://github.com/rubensgomes/rescreener/"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi (>=0.115.14)",
    "spacy (>=3.8.7,<4.0.0)"
]

[tool.poetry]
packages = [{include = "rescreener", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

